export const m4000 = [
    //used in cfp  added a digit after each code to use a single loop for component 
{code : 1010 , title:	"CAPITAL SOCIAL"},
{code : 1020 , title:	"RÉSERVES"},
{code : 1021 , title: "RÉSERVES LÉGALES"},
{code : 1022 , title: "RÉSERVES STATUTAIRES ET CONTRACTUELLES"},
{code : 1023 , title: "ECART DE RÉÉVALUATION"},
{code : 1030 , title:	"PROVIOSION POUR RISQUES BANCAIRES GÉNÉRAUX"},
{code : 1040 , title:	"BÉNÉFICE DE L'EXERCICE"},
{code : 1050 , title:	"REPORT A NOUVEAU CRÉDITEUR"},
{code : 1060 , title:	"DETTES SUBORDONNÉES"},
{code : 1070 , title:	"SOUS-TOTAL"},
{code : 1080 , title:	"PART NON LIBEREE DU CAPITAL"},
{code : 1090 , title:	"PERTE DE L'EXERCICE"},
{code : 1100 , title:	"IMMOBILISATIONS INCORPORELLES D'EXPLOITATION HORS DROIT AU BAIL"},
{code : 1110 , title:	"FRAIS D'ÉTABLISSEMENT"},
{code : 1120 , title:	"REPORT A NOUVEAU DEBITEUR"},
{code : 1130 , title:	"SOUS-TOTAL"},
{code : 1140 , title:	"TOTAL DES FONDS PROPRES (C=A-B)"},
{code : 1150 , title:	"COMPTES COURANTS DES ASSOCIES"},
{code : 1160 , title:	"RMPRUNTS OBLIGATAIRE EMIS ( au-delà de 5 ans)"},
{code : 1170 , title:	"BONS DE CAISSE ET BONS DE D'EPARGNE (clientèle)"},
{code : 1180 , title:	"DEPOTS DE LA CLIENTELE A TERME (au dela de 5 ans)"},
{code : 1190 , title:	"LIVRETS D'EPARGNE LOGMENTS"},
{code : 1200 , title:	"AUTRE LIVRETS D'EPARGNE STABLE"},
{code : 1210 , title:	"EXCEDENTS DES EMPRUNTS SUR LE PRETS DES BANQUES ET ETABLISSMENTS FINANCIERS (au dela de 5 ans)"},
{code : 1220 , title:	"TOTAL DES RESSOURCES PERMANENTES"},
{code : 1230 , title:	"TOTAL DES RESSOURCES STABLES (E=C+D)"},
{code : 1240 , title:	"IMMOBILISATIONS NETTES D'AMORTISSMENT ET DES PROVISIONS EVENTUELLES."},
{code : 1250 , title:	"TITRES DE PARTICIPATION ET DE FILIALES (NETS DE PROVISIONS CONSTITUEES)"},
{code : 1260 , title:	"PRETS PARTICIPATIFS"},
{code : 1270 , title:	"CREANCES A RISQUE POTENTIEL (NETTES DE PROVISIONS CONSTITUEES)"},
{code : 1280 , title:	"AUTRES CRENCES CLASSEES (NETTES DE PROVISIONS CONSTITUEES)"},
{code : 1290 , title:	"CREANCES COURANTES (au-delà de 5 ans)"},
{code : 1300 , title:	"CREDITS BAIL (au-delà de 5 ans)"},
{code : 1310 , title:	"EXCEDENTS DES PRETS SUR LES EMPRUNTS DES BANQUES ET ETABLISSMENTS FINANCIERS( au-delà de 5 ans)"},
{code : 1320 , title:	"OBLIGATIONS NON NEGOCIABLES ( au-delà de 5 ans)"},
{code : 1330 , title:	"ACTIONS NON NEGOCIABLES"},
{code : 1340 , title:	"TOTAL DES EMPLOIS STABLES"},
{code : 1350 , title:	"COEFFICIENT DES FONDS PROPRES ET DE RESSOURCES PERMANENTES (G=E/F)"}

]